---
name: Build
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read    # This is required for actions/checkout
  packages: write   # This is required for docker/build-push-action

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/audio-server

jobs:
  build-docker-images:
    name: Build {{ matrix.app }} Docker image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [audio-server, ui]
    steps:
      - name: Determine version
        id: version
        env:
          VERSION: 0.0.2
        run: |
          # Check if triggered by a pull request by checking if ${{ github.event.number }} is set
            if [ -n "${{ github.event.number }}" ]; then
                echo "version=${{ env.VERSION }}-pr${{ github.event.number }}" >> "${GITHUB_OUTPUT}"
            else
                echo "version=${{ env.VERSION }}" >> "${GITHUB_OUTPUT}"
            fi

      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm/v6, linux/arm/v7
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm/v6, linux/arm/v7
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.app }}
          tags: |
            type=raw,value=${{ steps.version.outputs.version }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.app }}
          file: ./${{ matrix.app }}/Dockerfile
          platforms: linux/arm/v6, linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
